# -*- coding: utf-8 -*-
"""eda through ydata_profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-FTtzJC4zxJmHYeabsCIuHS0dOvg6mp
"""

import pandas as pd
from ydata_profiling import ProfileReport
from google.colab import files

# Load your data
df = pd.read_csv('gurgaon_properties_cleaned_v2.csv').drop_duplicates()

# Create the report (don't display it in notebook)
profile = ProfileReport(df, title="Gurgaon Properties Report", explorative=True)

# Save as HTML (works fine)
profile.to_file("gurgaon_profile_report.html")

# Download it
files.download("gurgaon_profile_report.html")

!pip install -U ydata-profiling